{{- if eq .Values.agent.kind "DaemonSet" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "netvantage.fullname" . }}-agent
  labels:
    {{- include "netvantage.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  selector:
    matchLabels:
      {{- include "netvantage.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: agent
  template:
    metadata:
      labels:
        {{- include "netvantage.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: agent
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: agent
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                {{- toYaml .Values.agent.securityContext.capabilities.add | nindent 16 }}
          volumeMounts:
            - name: config-cache
              mountPath: /home/netvantage/.netvantage
      volumes:
        - name: config-cache
          emptyDir: {}
{{- end }}
